### ISSUE TITLE
peer access is not supported between two devices

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#1499] opened 2024-04-26 02:52 UTC
code : release  v0.9.0 
GPU 2 * A30
CUDA Driver version: 510.73.08
docker container: using the repo build image
Model: llama-7b

I try to run inference with 2 A30 but it reports error.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/4d163897-9358-4091-b729-daeb01264f24)

**Comment by sleepwalker2017** [comment] 2024-04-26 04:11
https://github.com/NVIDIA/TensorRT-LLM/issues/1034
this post solved my problem.

**Comment by byshiue** [comment] 2024-04-30 02:53
Thank you for the update. Close this issue since the issue is resolved.

**Closed** 2024-04-30 02:54 UTC

**Comment by sleepwalker2017** [comment] 2024-04-30 03:21
> Thank you for the update. Close this issue since the issue is resolved.

But what's the cause of this issue?

we benchmark disabling this option, the performance is 5% lower than enabling custom-all-reduce.

**Comment by byshiue** [comment] 2024-05-09 07:00
peer access is determined by your network topo. And custom allreudce is only supported when the peer access is supported.
