### ISSUE TITLE
transformers version

### ISSUE THREAD

**Issue by sihanwang41** [NVIDIA/TensorRT-LLM#385] opened 2023-11-14 21:49 UTC
I see the requirements pin to `transformers==4.33.1`, is there any plans for using latest version? Or is there any limitations that we have to pin specific version in TensorRT-LLM?

Thank you

**Comment by byshiue** [comment] 2023-11-16 00:26
We pin the version of most packages to prevent the unkown issues when version is updated. We will update the version periodically.  You can als try the latest transformers by yourself.

**Comment by byshiue** [comment] 2023-12-11 09:27
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 09:27 UTC
Labels: triaged
