### ISSUE TITLE
CMake Generate step failed

### ISSUE THREAD

**Issue by ThinkPadRiver** [NVIDIA/TensorRT-LLM#296] opened 2023-11-07 02:43 UTC
$python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt-9.1.0.4/
Looking in indexes: https://pypi.antfin-inc.com/simple/
Requirement already satisfied: build in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.0.3)
Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: transformers==4.31.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (4.31.0)
Requirement already satisfied: diffusers==0.15.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.15.0)
Requirement already satisfied: accelerate==0.20.3 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.20.3)
Requirement already satisfied: colored in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.2.3)
Requirement already satisfied: polygraphy in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.49.0)
Requirement already satisfied: onnx>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.15.0)
Requirement already satisfied: mpi4py in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (3.1.4)
Requirement already satisfied: tensorrt>=8.6.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (9.1.0.post12.dev4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (1.23.5)
Requirement already satisfied: cuda-python==12.2.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (12.2.0)
Requirement already satisfied: sentencepiece>=0.1.99 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.1.99)
Requirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (0.38.4)
Requirement already satisfied: lark in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (1.1.8)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (3.12.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.18.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (4.65.0)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.10/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (10.1.0)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.10/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (6.8.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==0.20.3->-r requirements.txt (line 5)) (5.9.0)
Requirement already satisfied: cython in /opt/conda/lib/python3.10/site-packages (from cuda-python==12.2.0->-r requirements.txt (line 12)) (3.0.5)
Requirement already satisfied: pyproject_hooks in /opt/conda/lib/python3.10/site-packages (from build->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from build->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.11.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2023.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /opt/conda/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->-r requirements.txt (line 2)) (12.3.52)
Requirement already satisfied: protobuf>=3.20.2 in /opt/conda/lib/python3.10/site-packages (from onnx>=1.12.0->-r requirements.txt (line 8)) (4.24.3)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.10/site-packages (from importlib-metadata->diffusers==0.15.0->-r requirements.txt (line 4)) (3.17.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch->-r requirements.txt (line 2)) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
-- The CXX compiler identification is GNU 8.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NVTX is disabled
-- Importing batch manager
-- Building PyTorch
-- Building Google tests
-- Building benchmarks
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- CUDA compiler: /usr/local/cuda/bin/nvcc
-- GPU architectures: 70-real;80-real;86-real;89-real;90-real
-- The CUDA compiler identification is NVIDIA 12.2.91
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found /usr/local/tensorrt-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvinfer.so
-- ==========================================================================================
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found nvparsers_LIB_PATH-NOTFOUND
-- ==========================================================================================
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- Found MPI_CXX: /opt/conda/lib/libmpicxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- COMMON_HEADER_DIRS: /brc-nas-workspace/263095/TensorRT-LLM/cpp;/usr/local/cuda/include
-- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0
-- Found Python3: /opt/conda/bin/python3.10 (found version "3.10.13") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python executable at /opt/conda/bin/python3.10
-- Found Python libraries at /opt/conda/lib
-- Found CUDA: /usr/local/cuda (found version "12.2") 
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91") 
-- Caffe2: CUDA detected: 12.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 12.2
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 79a3de5a
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90
CMake Warning at /opt/conda/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /opt/conda/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:281 (find_package)

-- Found Torch: /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch.so  
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0
-- Building for TensorRT version: 9.1.0, library version: 9
-- Using MPI_CXX_INCLUDE_DIRS: /opt/conda/include
-- Using MPI_CXX_LIBRARIES: /opt/conda/lib/libmpicxx.so;/opt/conda/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- USE_CXX11_ABI: False
-- The C compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /opt/conda/bin/python3.10 (found version "3.10.13") found components: Interpreter 
-- ========================= Importing and creating target nvonnxparser ==========================
-- Looking for library nvonnxparser
-- Library that was found /usr/local/tensorrt-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvonnxparser.so
-- ==========================================================================================
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCCL_LIB
    linked by target "tensorrt_llm_static" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "tensorrt_llm" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "runtime_src" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm/runtime
    linked by target "nvinfer_plugin_tensorrt_llm" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm/plugins

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/brc-nas-workspace/xxx/TensorRT-LLM/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/brc-nas-workspace/xxx/TensorRT-LLM/./scripts/build_wheel.py", line 149, in main
    build_run(
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON"  -DTRT_LIB_DIR=/usr/local/tensorrt-9.1.0.4//targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt-9.1.0.4//include -S "/brc-nas-workspace/263095/TensorRT-LLM/cpp"' returned non-zero exit status 1.

**Comment by Shixiaowei02** [comment] 2023-11-07 05:38
> $python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt-9.1.0.4/ Looking in indexes: https://pypi.antfin-inc.com/simple/ Requirement already satisfied: build in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.0.3) Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.1.0) Requirement already satisfied: transformers==4.31.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (4.31.0) Requirement already satisfied: diffusers==0.15.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.15.0) Requirement already satisfied: accelerate==0.20.3 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.20.3) Requirement already satisfied: colored in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.2.3) Requirement already satisfied: polygraphy in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.49.0) Requirement already satisfied: onnx>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.15.0) Requirement already satisfied: mpi4py in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (3.1.4) Requirement already satisfied: tensorrt>=8.6.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (9.1.0.post12.dev4) Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (1.23.5) Requirement already satisfied: cuda-python==12.2.0 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (12.2.0) Requirement already satisfied: sentencepiece>=0.1.99 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.1.99) Requirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (0.38.4) Requirement already satisfied: lark in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (1.1.8) Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (3.12.4) Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.18.0) Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (23.1) Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (6.0) Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2023.10.3) Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2.28.1) Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.13.3) Requirement already satisfied: safetensors>=0.3.1 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.4.0) Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (4.65.0) Requirement already satisfied: Pillow in /opt/conda/lib/python3.10/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (10.1.0) Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.10/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (6.8.0) Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate==0.20.3->-r requirements.txt (line 5)) (5.9.0) Requirement already satisfied: cython in /opt/conda/lib/python3.10/site-packages (from cuda-python==12.2.0->-r requirements.txt (line 12)) (3.0.5) Requirement already satisfied: pyproject_hooks in /opt/conda/lib/python3.10/site-packages (from build->-r requirements.txt (line 1)) (1.0.0) Requirement already satisfied: tomli>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from build->-r requirements.txt (line 1)) (2.0.1) Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (4.8.0) Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (1.12) Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (3.2.1) Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.11.2) Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2023.10.0) Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105) Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105) Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105) Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (8.9.2.26) Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.3.1) Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (11.0.2.54) Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (10.3.2.106) Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (11.4.5.107) Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.0.106) Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.18.1) Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (12.1.105) Requirement already satisfied: triton==2.1.0 in /opt/conda/lib/python3.10/site-packages (from torch->-r requirements.txt (line 2)) (2.1.0) Requirement already satisfied: nvidia-nvjitlink-cu12 in /opt/conda/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->-r requirements.txt (line 2)) (12.3.52) Requirement already satisfied: protobuf>=3.20.2 in /opt/conda/lib/python3.10/site-packages (from onnx>=1.12.0->-r requirements.txt (line 8)) (4.24.3) Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.10/site-packages (from importlib-metadata->diffusers==0.15.0->-r requirements.txt (line 4)) (3.17.0) Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 2)) (1.1.1) Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2.0.4) Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (3.4) Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (1.26.16) Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2023.7.22) Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch->-r requirements.txt (line 2)) (1.3.0) WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv -- The CXX compiler identification is GNU 8.3.1 -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done -- NVTX is disabled -- Importing batch manager -- Building PyTorch -- Building Google tests -- Building benchmarks -- Looking for a CUDA compiler -- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc -- CUDA compiler: /usr/local/cuda/bin/nvcc -- GPU architectures: 70-real;80-real;86-real;89-real;90-real -- The CUDA compiler identification is NVIDIA 12.2.91 -- Detecting CUDA compiler ABI info -- Detecting CUDA compiler ABI info - done -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped -- Detecting CUDA compile features -- Detecting CUDA compile features - done -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91") -- Performing Test CMAKE_HAVE_LIBC_PTHREAD -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed -- Looking for pthread_create in pthreads -- Looking for pthread_create in pthreads - not found -- Looking for pthread_create in pthread -- Looking for pthread_create in pthread - found -- Found Threads: TRUE -- ========================= Importing and creating target nvinfer ========================== -- Looking for library nvinfer -- Library that was found /usr/local/tensorrt-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvinfer.so -- ========================================================================================== -- ========================= Importing and creating target nvuffparser ========================== -- Looking for library nvparsers -- Library that was found nvparsers_LIB_PATH-NOTFOUND -- ========================================================================================== -- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag -- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag -- Found MPI_CXX: /opt/conda/lib/libmpicxx.so (found version "3.1") -- Found MPI: TRUE (found version "3.1") -- COMMON_HEADER_DIRS: /brc-nas-workspace/263095/TensorRT-LLM/cpp;/usr/local/cuda/include -- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0 -- Found Python3: /opt/conda/bin/python3.10 (found version "3.10.13") found components: Interpreter Development Development.Module Development.Embed -- Found Python executable at /opt/conda/bin/python3.10 -- Found Python libraries at /opt/conda/lib -- Found CUDA: /usr/local/cuda (found version "12.2") -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91") -- Caffe2: CUDA detected: 12.2 -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc -- Caffe2: CUDA toolkit directory: /usr/local/cuda -- Caffe2: Header version is: 12.2 -- /usr/local/cuda/lib64/libnvrtc.so shorthash is 79a3de5a -- USE_CUDNN is set to 0. Compiling without cuDNN support -- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90 CMake Warning at /opt/conda/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message): static library kineto_LIBRARY-NOTFOUND not found. Call Stack (most recent call first): /opt/conda/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found) CMakeLists.txt:281 (find_package)
> 
> -- Found Torch: /opt/conda/lib/python3.10/site-packages/torch/lib/libtorch.so -- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0 -- Building for TensorRT version: 9.1.0, library version: 9 -- Using MPI_CXX_INCLUDE_DIRS: /opt/conda/include -- Using MPI_CXX_LIBRARIES: /opt/conda/lib/libmpicxx.so;/opt/conda/lib/libmpi.so -- CMAKE_SYSTEM_PROCESSOR: x86_64 -- USE_CXX11_ABI: False -- The C compiler identification is GNU 8.3.1 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Found Python: /opt/conda/bin/python3.10 (found version "3.10.13") found components: Interpreter -- ========================= Importing and creating target nvonnxparser ========================== -- Looking for library nvonnxparser -- Library that was found /usr/local/tensorrt-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvonnxparser.so -- ========================================================================================== -- Configuring done CMake Error: The following variables are used in this project, but they are set to NOTFOUND. Please set them or make sure they are set and tested correctly in the CMake files: NCCL_LIB linked by target "tensorrt_llm_static" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm linked by target "tensorrt_llm" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm linked by target "runtime_src" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm/runtime linked by target "nvinfer_plugin_tensorrt_llm" in directory /brc-nas-workspace/263095/TensorRT-LLM/cpp/tensorrt_llm/plugins
> 
> -- Generating done CMake Generate step failed. Build files cannot be regenerated correctly. Traceback (most recent call last): File "/brc-nas-workspace/xxx/TensorRT-LLM/./scripts/build_wheel.py", line 248, in main(**vars(args)) File "/brc-nas-workspace/xxx/TensorRT-LLM/./scripts/build_wheel.py", line 149, in main build_run( File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DTRT_LIB_DIR=/usr/local/tensorrt-9.1.0.4//targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt-9.1.0.4//include -S "/brc-nas-workspace/263095/TensorRT-LLM/cpp"' returned non-zero exit status 1.

The error part of above message is:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCCL_LIB
```
Please try to use the docker image and it will make the work easier.

**Comment by ThinkPadRiver** [comment] 2023-11-07 06:11
in my case，official docker image instruction is not available

**Comment by ThinkPadRiver** [comment] 2023-11-07 09:22
follow the documnet https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html#rhel_centos fix the error

**Comment by byshiue** [comment] 2023-11-07 09:31
Thank you for update. It looks the issue is solved. Close this issue. Feel free to reopen if needed.

**Closed by byshiue** 2023-11-07 09:31 UTC
Labels: build
