### ISSUE TITLE
NameError: name 'layers_range' is not defined

### ISSUE THREAD

**Issue by jkl375** [NVIDIA/TensorRT-LLM#541] opened 2023-12-04 08:41 UTC
https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/generation_mixin.py#L548

When I run the code for building llama with lora, find 'layers_range' is not defined in function prepare_basic_inputs.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/54523287/1a268c39-27c7-49a8-90c1-ff910db25d62)

I think 'layers_range' should be changed to 'self.layers_range'  in class GenerationMixin.

**Comment by QiJune** [comment] 2023-12-05 01:36
Yes, the issue is fixed at internal repo, and will be pushed to github main branch in a week. You could fix it locally by:

```
        if use_lora_plugin:
            lora_weights_pointers = []
            lora_ranks = []
            layers_range = self.get_transformer_layers(mapping, num_layers)
            for i in layers_range:
```

**Comment by byshiue** [comment] 2023-12-25 09:08
This issue should be fixed in latest main codes. Close this bug. If you still have issue, feel free to ask here and we will reopen this issue at the moment.

**Closed by byshiue** 2023-12-25 09:08 UTC
Labels: triaged
