### ISSUE TITLE
Smoothquant per-tensor checkpoint creation fails for LLaMA-13B

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1338] opened 2024-03-22 20:24 UTC
### System Info

p4d, 8xGPU : NVIDIA A100 40GB

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Installation
`python -m pip install tensorrt_llm==0.8.0 --extra-index-url https://pypi.nvidia.com`

2. Create checkpoint
`python ~/examples/llama/convert_checkpoint.py --model_dir ~/Llama-2-13b-chat-hf  --output_dir ~/checkpoints/fp16-tp4-sq-pertensor --dtype float16 --tp_size 4 --workers 8 --smoothquant 0.5`

### Expected behavior

Successful checkpoint creation

### actual behavior

 np.array([cur_per_channel_value], dtype=np.float32).reshape(col_shape)
ValueError: cannot reshape array of size 15360 into shape (1,3840)

Line:
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.8.0/examples/llama/convert_checkpoint.py#L762

results[prefix + "per_channel_scale"] = torch.from_numpy(
            np.array([cur_per_channel_value], dtype=np.float32).reshape(col_shape)
        ).clone()
        

### additional notes

N/A

**Comment by byshiue** [comment] 2024-03-27 01:34
Thank you for reporting the issue. The issue is fixed in latest main brach update, and you can refer here https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/convert.py#L572-L583 if you want to fix it on 0.8.0 branch.

**Closed by byshiue** 2024-03-27 01:34 UTC
Labels: bug
