### ISSUE TITLE
TensorRT 9 in PyTorch NGC 

### ISSUE THREAD

**Issue by david-PHR** [NVIDIA/TensorRT-LLM#337] opened 2023-11-09 17:27 UTC
Hello,

One benefits of TensorRT LLM is to used the latest TensorRT 9.0 features (bf16, fp8...). Unfortunately the PyTorch NGC container 23.10 doesn't support TensorRT 9. Do you know if this version will be supported in the PyTorch NGC 23.11 container?

Thanks

**Comment by byshiue** [comment] 2023-11-10 09:42
@ncomly-nvidia Do you have idea?

**Comment by ncomly-nvidia** [comment] 2023-11-22 00:59
Hi @david-PHR , TRT 9 is built specifically for TRT-LLM so it won't be added to the general NGC PyTorch container, however, we do have a container packaged with TRT-LLM, TRT 9, & Triton! Check out the Triton [23.10-trtllm-python-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags)
on NGC! Going forward the Triton container for TRT-LLM will always have the latest.

& don't worry, the rest of the NGC containers will have the latest TRT versions soon :)

**Comment by byshiue** [comment] 2023-12-11 09:40
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 09:40 UTC
Labels: triaged
