### ISSUE TITLE
request failed when max batch size > 8 

### ISSUE THREAD

**Issue by yangelaboy** [NVIDIA/TensorRT-LLM#718] opened 2023-12-21 09:38 UTC
- version: 0.5.0

- model: llama-7b

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16263873/3bc96931-a787-4f3a-8f13-1c59894773c6)

**Comment by kaiyux** [comment] 2023-12-22 06:50
Can you try the latest main branch?

**Comment by yangelaboy** [comment] 2023-12-25 09:41
@kaiyux ok，I will try with latest version, thx！

**Comment by yangelaboy** [comment] 2023-12-26 07:15
@kaiyux hello，I run tensorrt-llm-backend with version 0.6.1, but got an error as follow:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16263873/eaa4557f-525b-4d7d-bf1d-2a6f7df1ab4e)

**Comment by byshiue** [comment] 2023-12-26 09:20
Have you rebuilt the engine on trt llm 0.6.1?

**Comment by yangelaboy** [comment] 2023-12-27 01:46
@byshiue yes，rebuilt the engine on trt llm 0.6.1

**Comment by byshiue** [comment] 2023-12-27 03:49
Could you try 0.7.1 tag, which is released yesterday?

**Comment by yangelaboy** [comment] 2024-01-16 02:49
@byshiue ok

**Comment by yangelaboy** [comment] 2024-01-26 02:45
v0.7.1 is ok with bath size > 8

**Comment by byshiue** [comment] 2024-01-30 08:52
Thank you for the update. Close this bug since the issue is fixed in v0.7.1.

**Closed by byshiue** 2024-01-30 08:52 UTC
Labels: triaged
