### ISSUE TITLE
Quantize script not working for CodeLlama 34B

### ISSUE THREAD

**Issue by atyshka** [NVIDIA/TensorRT-LLM#239] opened 2023-11-01 18:24 UTC
I am trying to quantize the CodeLlama 34B model for use with TensorRT. Running this command:
`python3 hf_llama_convert.py -i /code/tensorrt_llm/models/codellama/ -o smooth_llama_34B/sq0.5/ -sq 0.5 --tensor-parallelism 2 --storage-type fp16`
I encounter this issue:
```
Traceback (most recent call last):                                                                                                                                                                                    
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker                                                                                                                                             
    result = (True, func(*args, **kwds))                                                                                                                                                                              
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar                                                                                                                                         
    return list(itertools.starmap(args[0], args[1]))                                                                                                                                                                  
  File "/code/tensorrt_llm/examples/llama/convert.py", line 292, in split_and_save_weight                                                                                                                             
    val = val.reshape(hidden_dim, 3, local_dim)                                                                                                                                                                       
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)       
```
It seems that for the smaller 7B Llama models, the attention weight matrix shape is (4096, 12288), for the 13B Llama models, the shape is (5120, 15360), but for the 34B model, the attention weight shape is (8192, 10240), which is not divisible by 3. Why is TRT trying to split the weights in 3? Is this to separate the query, key, and value? If so, I don't get why CodeLlama would not also have dimensions divisible by 3.

**Comment by byshiue** [comment] 2023-11-02 01:11
Do you try on `main` branch? It should be a bug for GQA/MQA and it is fixed in latest main branch.

**Comment by atyshka** [comment] 2023-11-03 14:16
I am still getting the issue on the latest version of main. If you add a print statement `print(val.shape)` after [line 272 of convert.py](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/convert.py#L272) can you reproduce my shape and error?

**Comment by byshiue** [comment] 2023-11-04 14:37
> I am still getting the issue on the latest version of main. If you add a print statement `print(val.shape)` after [line 272 of convert.py](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/convert.py#L272) can you reproduce my shape and error?

Can you check again that you really use the `main` branch? I ask this question because the code line your share (line 272 of convert.py) is on `release/0.5.0`.

**Comment by atyshka** [comment] 2023-11-04 14:59
Sorry for linking to the wrong place. But yes, git branch shows I'm on main, and I rebuilt and reinstalled the wheel after checking out

**Comment by Tracin** [comment] 2023-11-06 07:24
> Sorry for linking to the wrong place. But yes, git branch shows I'm on main, and I rebuilt and reinstalled the wheel after checking out

I reproduce this error on the latest main branch, I will try to fix it.

**Comment by Tracin** [comment] 2023-11-06 07:58
> Sorry for linking to the wrong place. But yes, git branch shows I'm on main, and I rebuilt and reinstalled the wheel after checking out

Please try add `--multi-query-mode` for `hf_llama_convert.py`.

**Closed** 2023-11-08 07:30 UTC
Labels: triaged
