### ISSUE TITLE
Failed to run batch inference

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#42] opened 2023-10-20 10:22 UTC
I'm running llama-7b on A30 single GPU.
When the batch is 1, it runs well.
I try to run with input ids with shape[2, 32], and input_lengths is tensor([32, 32], but it complains like this:

```
torch.Size([2, 32]) tensor([32, 32], device='cuda:0', dtype=torch.int32)
decoder.setup 2 32 50 1
[10/20/2023-10:18:29] [TRT] [E] 3: [executionContext.cpp::setInputShape::2257] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2257, condition: engineDims.d[i] == dims.d[i] Static dimension mismatch while setting input shape.)
Traceback (most recent call last):
  File "/data/trt-llm/TensorRT-LLM/examples/llama/run.py", line 299, in <module>
    generate(**vars(args))
  File "/data/trt-llm/TensorRT-LLM/examples/llama/run.py", line 259, in generate
    output_gen_ids = decoder.decode(input_ids,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign input_ids with shape torch.Size([2, 32]), engine supports [min, opt, max] = [(1, 1), (1, 8), (1, 16384)]
```

Seems the max_batch_size = 8 in the build phase is not correctly set to the engine.

Here is my convert script:

```shell
python build.py --model_dir /data/models/llama-7b-hf/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu/
```

**Comment by jdemouth-nvidia** [comment] 2023-10-20 10:36
Thanks @sleepwalker2017 . Does it fail in the `build.py` invocation? Or, does it fail in a run command? If that's the latter, can you provide us with the command-line, please?

**Comment by sleepwalker2017** [comment] 2023-10-20 10:57
> Thanks @sleepwalker2017 . Does it fail in the `build.py` invocation? Or, does it fail in a run command? If that's the latter, can you provide us with the command-line, please?

The build is ok, and run inference with single batch is ok.

Run inference with 2 batch failed.

The command is:
```
python3 run.py --max_output_len=96 \
               --tokenizer_dir /data/models/llama-7b-hf \
               --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
```

**Comment by wm2012011492** [comment] 2023-10-20 11:01
Hi @sleepwalker2017 , I guess you modified the run.py script to support bs > 1, right? Since your engine is generated with --remove_input_padding, you need some different processing like https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/summarize.py#L178. 
Another workaround is to not use --remove_input_padding and re-build the engine.

**Comment by jdemouth-nvidia** [comment] 2023-10-20 11:19
@sleepwalker2017 , excuse me if you already know what `--remove_input_padding` means, if not, it's described here: https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/gpt_attention.md#padded-and-packed-tensors.

**Comment by qihang720** [comment] 2023-10-20 11:52
I have a similar question.

I'm running in A40, and try to performance different batches, but when I run in  `batch _size 8, input_output_len "2048,2048"`, caused oom, I'm curious why memory occupancy too much，it's just 7b model.

`python benchmark.py -m llama_7b --mode plugin --batch_size "1;2;4;8" --input_output_len "128,2048;2048,2048" --csv --max_input_len 2048 --max_output_len 2048`

**Comment by wm2012011492** [comment] 2023-10-20 13:55
Hi @qihang720 , I think it's a different question. Please also specify the --max_batch_size like 8 in your command. Otherwise the default max_batch_size is 128 for llama_7b as defined in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/allowed_configs.py#L248

**Comment by jdemouth-nvidia** [comment] 2023-10-20 14:18
@qihang720 , if @wm2012011492 's suggestion does not fix your issue, do you mind opening another issue, please?

**Comment by qihang720** [comment] 2023-10-23 02:03
> @qihang720 , if @wm2012011492 's suggestion does not fix your issue, do you mind opening another issue, please?

Hi, @wm2012011492 @jdemouth-nvidia I open a new issue, https://github.com/NVIDIA/TensorRT-LLM/issues/67

**Comment by sleepwalker2017** [comment] 2023-10-23 02:15
> https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/summarize.py#L178

Hello, what is the relationship between non-padding and batching?

I use 2 batches with the same input ids. Do I still need to do extra work?

**Comment by sleepwalker2017** [comment] 2023-10-23 02:28
To run a batch inference, the input_ids must be a list? not a tensor?

I must call another api decode_batch?

**Comment by jdemouth-nvidia** [comment] 2023-10-23 05:08
Hi @sleepwalker2017 , 

I'm not sure to understand the question, so my apologies if the answer does not correspond to what you expect. When you enable `remove_input_padding`, you must provide TensorRT-LLM with 2 tensors. The first tensor contains the tokens from the two sequences (batch 2) without any padding token. The second one contains the length of each sequence. For example, if we have:

```
SEQ0 = Token0, Token1, Pad,    Pad    # Sequence length = 2
SEQ1 = Token2, Token3, Token4, Token5 # Sequence length = 4
```

The two tensors should be:

```
Tokens = [Token0, Token1, Token2, Token3, Token4, Token5]
Lengths = [2, 4]
```

Both are tensors. Does it make more sense?

Thanks,
Julien

**Comment by sleepwalker2017** [comment] 2023-10-23 06:54
> Tokens

My input is like this:

```
SEQ0 = Token0, Token1, Token2    # Sequence length = 3
SEQ1 =  Token0, Token1, Token2    # Sequence length = 3
```
In my test case, the input tensor is in shape [2, 3].  After I reshape it to (1, -1), the inference is ok. Thank you.

**Comment by byshiue** [comment] 2023-12-11 07:47
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 07:47 UTC
Labels: triaged
