### ISSUE TITLE
Non-block streamer in python runtime

### ISSUE THREAD

**Issue by wang90063** [NVIDIA/TensorRT-LLM#111] opened 2023-10-25 07:59 UTC
In the python runtime, stream_decode is implemented, which is a generator. 

But, if the token_id of stream_decode  is returned, the tokenizer decoding should be applied afterwards.

For non-block way, it is possible to start two threads, which is for model generation and tokenizer decode, and the two threads share one queue.

To implemnt the above funciton, the shared queue should be passed into the stream_decodoe allowing the output tokenid to push.

But this way change the source code, is there another way to realize non-block streamer without changing source code?

**Comment by jdemouth-nvidia** [comment] 2023-10-25 10:39
For more flexibility and better performance, we recommend to use the C++ runtime. 

That said, we do not support that use case for now. Does it take a lot of time to decode from the token id? In other words, is that really a game changer in terms of performance?

**Comment by ywran** [comment] 2023-10-25 11:18
It is indeed the performance bottleneck, since the decoding is needed at every generation token. I will give an experiment :)

**Comment by wang90063** [comment] 2023-10-25 11:22
It is literaly the performance bottleneck, since the decoding is applied after each token is generated. 

I will give an experiment. Let's discuss afterwards.

**Comment by jdemouth-nvidia** [comment] 2023-10-25 14:06
Let’s wait for the experiment, indeed. If the generation pass (forward of the LLM) takes 99% of the time and the decoding of the token ID a single %, that’s a different story that if it is 50%-50% ;)

**Comment by ywran** [comment] 2023-10-26 03:29
- Model: codellama-7b-python
- GPU: A800

I notice that the straming generation demo is shown in the example/llama/run.py by set streaming.
Also, the streaming_interval control the tokenization docoding frequency. Let's see the follwing results

generated token numbers:  500

| streaming interval                       |latency (seconds)|  
|:----------------------------|:-----------------:|
| 1|     6.09    |
| 100|     3.438 		     |  

BTW,impressive inference speed :)

**Comment by wang90063** [comment] 2023-10-26 03:34
- Model: codellama_7b
- gpu : a800
- generated token number: 500

I notice that the streaminig demo is presented in the examples/llama/run.py by setting --streaming.
Also, straming_interval controls the tokenization decoding frequency. Let's see the following results

| straming_interval  |latency (seconds)|  
|:----------------------------|:----------------------------|
| 1|     6.093	          | 
| 100 |     3.138 	|  

BTW, impressive inference speed :)

**Comment by ywran** [comment] 2023-10-30 10:37
@jdemouth-nvidia Hi, from the experiment results, it seems that non-block streaming for python runtime is neccesary.

**Comment by byshiue** [comment] 2023-12-11 08:14
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 08:14 UTC
Labels: triaged
