### ISSUE TITLE
gptManagerBenchmark.cpp still generating tokens after eos_id for llama2

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#355] opened 2023-11-11 11:03 UTC
1. I prepared simple dataset for benchmark
```json
[{"input_ids": [1, 887, 526, 1371, 8159, 20255, 29889, 673, 373, 590, 5155], "output_len": 512}]
```

2. I modified src to print output tokens and add info about eos/pad ids

```diff
diff --git a/benchmarks/cpp/gptManagerBenchmark.cpp b/benchmarks/cpp/gptManagerBenchmark.cpp
index e409cd7..339784a 100644
--- a/benchmarks/cpp/gptManagerBenchmark.cpp
+++ b/benchmarks/cpp/gptManagerBenchmark.cpp
@@ -33,6 +33,7 @@
 #include <iostream>
 #include <nlohmann/json.hpp>
 #include <string>
+#include <iostream>
 
 using namespace tensorrt_llm::runtime;
 using namespace tensorrt_llm::batch_manager;
@@ -42,6 +43,8 @@ using namespace tensorrt_llm::mpi;
 namespace tc = tensorrt_llm::common;
 namespace trt = nvinfer1;
 
+const int32_t kEosId = 2;
+
 // Class holding all infos regarding a single work item.
 // This includes the original request, associated response factor
 // and state.
@@ -413,6 +416,23 @@ public:
     void sendResponse(uint64_t requestId, std::list<NamedTensor> const& response_tensors, bool final_response,
         const std::string& errMsg)
     {
+        for (auto& tensor: response_tensors) {
+            TLLM_LOG_INFO(tensor.name);
+            auto shape = tensor.tensor->getShape();
+            TLLM_LOG_INFO("shape");
+            std::cout << "[";
+            for (auto i = 0; i < shape.nbDims; i++)
+              std::cout << shape.d[i] << ", ";
+            std::cout << "]" << std::endl;
+            TLLM_LOG_INFO("type");
+            auto type = tensor.tensor->getMemoryType();
+            std::cout << static_cast<int32_t>(type) << std::endl;
+            TLLM_LOG_INFO("data");
+            std::cout << "[";
+            for (auto i = 0; i < tensor.tensor->getSize(); i++)
+              std::cout << reinterpret_cast<const int*>(tensor.tensor->data())[i] << ", ";
+            std::cout << "]" << std::endl;
+        }
         std::string errStr = std::string("Failed to send response for requestId: ") + std::to_string(requestId);
         try
         {
@@ -494,7 +514,11 @@ void benchmarkGptManager(std::string const& modelName, std::filesystem::path con
         auto input_ids_tensor = NamedTensor(nvinfer1::DataType::kINT32, input_ids_shape, "input_ids", input_ids.data());
         auto request_output_len_tensor
             = NamedTensor(nvinfer1::DataType::kINT32, {1, 1}, "request_output_len", &request_output_len);
-        std::vector<NamedTensor> tensors = {input_ids_tensor, request_output_len_tensor};
+        auto end_id_tensor
+            = NamedTensor(nvinfer1::DataType::kINT32, {1, 1}, "end_id", &kEosId);
+        auto pad_id_tensor
+            = NamedTensor(nvinfer1::DataType::kINT32, {1, 1}, "pad_id", &kEosId);
+        std::vector<NamedTensor> tensors = {input_ids_tensor, request_output_len_tensor, end_id_tensor, pad_id_tensor};
         tensors_list.push_back(tensors);
     }
 
```

3. Run bench
```shell
CUDA_VISIBLE_DEVICES=3 ./gptManagerBenchmark -m llama2 --engine_dir /code/tensorrt_llm/examples/llama/llama7b --dataset /code/tensorrt_llm/benchmarks/cpp/dataset_small.json
```

Output is
```shell
[TensorRT-LLM][INFO] output_ids
[TensorRT-LLM][INFO] shape
[1, 1, 523, ]
[TensorRT-LLM][INFO] type
1
[TensorRT-LLM][INFO] data
[1, 887, 526, 1371, 8159, 20255, 29889, 673, 373, 590, 5155, 322, 3867, 592, 411, 278, 5181, 2472, 29889, 13, 2, 1, 13, 29902, 505, 263, 1139, 1048, 278, 14826, 29821, 579, 29889, 1815, 366, 3113, 3867, 592, 411, 278, 29821, 579, 363, 9826, 29973, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 2, 1, 13, 13, 2, 1, 13, 13, 2, 1, 13, 13, 13, 2, 1, 13, 13, 13, 2, 1, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, ]
[BENCHMARK] num_samples(ms) 1
[BENCHMARK] total_latency(ms) 5721.09
[BENCHMARK] seq_throughput(seq/sec) 0.17
[BENCHMARK] avg_sequence_latency(ms) 5721.07
[BENCHMARK] token_throughput(token/sec) 89.49
[TensorRT-LLM][INFO] Terminate signal received, worker thread exiting.
```

You can see that data looks strange. It has a lot of eos tokens (2) but after eos tokens trtllm generates regular tokens again.
```python
[1, 887, 526, 1371, 8159, 20255, 29889, 673, 373, 590, 5155, 322, 3867, 592, 411, 278, 5181, 2472, 29889, 13, 2, 1, 13, 29902, 505, 263, 1139, 1048, 278, 14826, 29821, 579, 29889, 1815, 366, 3113, 3867, 592, 411, 278, 29821, 579, 363, 9826, 29973, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 2, 1, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 2, 1, 13, 13, 2, 1, 13, 13, 2, 1, 13, 13, 13, 2, 1, 13, 13, 13, 2, 1, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, ]
```

So my question is: why doesn't getting the eos token stop the generation?

**Comment by Roysky** [comment] 2023-11-13 13:32
the same question to Baichuan2-13B-chat model.   I think it is padded to the length of output_len.
 
so my question is: 

**when calc the token_throughput(token/sec) , the total tokens of output include the number of padding tokens.**

***

```cpp
 void calculateMetrics()
    {
        mNumSamples = mRequestBenchInfos.size();
        mTotalLatency = std::chrono::duration<float, std::milli>(mEnd - mStart).count();
        mSeqThroughput = mNumSamples / (mTotalLatency / 1000);
        mAvgSeqLatency = 0;
        int totalOutputTokens = 0;
        for (auto reqInfo : mRequestBenchInfos)
        {
            mAvgSeqLatency += reqInfo.second.latency;
            totalOutputTokens += reqInfo.second.outputLength;
            printf("[outputLength]  %d\n", reqInfo.second.outputLength);
        }
        mAvgSeqLatency /= mNumSamples;
        mTokenThroughput = totalOutputTokens / (mTotalLatency / 1000);
    }

    void report()
    {
        printf("[BENCHMARK] num_samples(ms) %d\n", mNumSamples);
        printf("[BENCHMARK] total_latency(ms) %.2f\n", mTotalLatency);
        printf("[BENCHMARK] seq_throughput(seq/sec) %.2f\n", mSeqThroughput);
        printf("[BENCHMARK] avg_sequence_latency(ms) %.2f\n", mAvgSeqLatency);
        printf("[BENCHMARK] token_throughput(token/sec) %.2f\n", mTokenThroughput);
    }
```

**Comment by akhoroshev** [comment] 2023-11-13 16:56
> when calc the token_throughput(token/sec) , the total tokens of output include the number of padding tokens.

I think that it is not padding tokens. If they were all equal to pad then it would be padding. But that's not true for my case.

You can see different tokens. I'm guessing this model (benchmark) ignores the information about the eos/pad tokens I'm passing.

**Comment by Shixiaowei02** [comment] 2023-11-15 02:23
Hi @akhoroshev , I have reproduced the problem you described. The reasons are that:

1. The shape needs to be changed from `[1, 1]` to `[1]` .
2. If `end_id` appears in the prompt, it will be ignored.

We will confirm this behavior and adopt your code to add options for this benchmark. I will close this issue, if you have further questions, please reopen it or reply. Thanks!

**Closed** 2023-11-16 03:30 UTC
Labels: invalid, triaged
