### ISSUE TITLE
Would it be possible to support more than one eos_ids?

### ISSUE THREAD

**Issue by wangruohui** [NVIDIA/TensorRT-LLM#120] opened 2023-10-25 13:15 UTC
As titled. 

I hope during inference, the inference engine would be possible to stop after meeting one of the candidate "stoping ids". Or in pseudo-code:

```
if cur_id_of_current_sentence in list_of_stop_ids:
    # stop generating current sentence
```

It seems from current examples and codes, https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L645, only single `eos_id` is allowed.

This is useful because some chat models may use ids other than the eos id to separate words from human users and models. Model should stop generating when meeting such separators.

**Comment by jdemouth-nvidia** [comment] 2023-10-25 14:12
Is that different from the `stop_word_list` where each word would be a single token?

**Comment by juney-nvidia** [comment] 2023-10-25 15:19
To provide some additional information based on what Julien suggested, you can refer to this documentation to figure out how to use stop_word_list in the C++ runtime workflow.
https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/docs/source/gpt_runtime.md

**Comment by wangruohui** [comment] 2023-10-30 10:31
That's OK. Will it also be supported in Python workflow?

**Comment by byshiue** [comment] 2023-10-30 14:33
> That's OK. Will it also be supported in Python workflow?

Yes. Here is an example https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/gpt/run.py#L255-L258.

**Comment by byshiue** [comment] 2023-12-11 08:17
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 08:17 UTC
Labels: triaged
