### ISSUE TITLE
build failure: libnvparsers not found in tensorRT 9.1.0.4

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#64] opened 2023-10-23 00:02 UTC
cmake configuration reports:
```
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found nvparsers_LIB_PATH-NOTFOUND
-- ==========================================================================================
```

and I can not find libparsers.so in tensorRT package, only libonnxparser exists:
```
./targets/x86_64-linux-gnu/lib/libnvonnxparser.so.9
./targets/x86_64-linux-gnu/lib/libnvonnxparser.so
./targets/x86_64-linux-gnu/lib/libnvonnxparser.so.9.1.0
./targets/x86_64-linux-gnu/lib/stubs/libnvonnxparser.so
./targets/x86_64-linux-gnu/lib/libnvonnxparser_static.a

```

**Comment by juney-nvidia** [comment] 2023-10-23 00:33
@forrestjgq  pls share your environment and steps of reproducing this error. It is easier for us to get the clue of this error.

**Comment by forrestjgq** [comment] 2023-10-23 02:07
Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

nvidia-smi shows:
```
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
```

I use `nvcr.io/nvidia/pytorch:23.08-py3`  as base image to create a container:
```
image="nvcr.io/nvidia/pytorch:23.08-py3"
name=$1

docker run \
    --runtime=nvidia\
    -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
    --privileged \
    -v /home/gqjiang:/home/gqjiang:rw \
    -v /data:/data:rw \
    -it --net=host --ulimit core=-1 --security-opt seccomp=unconfined --detach-keys=ctrl-i,c \
    --name $name \
    $image \
    bash

```

then inside it I ran:
```
    3  cd /home/gqjiang/src/llmtest/
    4  cd docker/common/
    5  ls
    6  bash install_base.sh
    7  bash install_cmake.sh 
    8  bash install_tensorrt.sh 
    9  bash install_polygraphy.sh 
   10  bash install_pytorch.sh skip
   11  cd ../..
   12  python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt
```

The full log is attached [llm.log](https://github.com/NVIDIA/TensorRT-LLM/files/13065443/llm.log), as you will see, I interrupted it because:
1. nvparser NOT FOUND
2. it takes too long to build last 8 cu files, toooooooo long like it never ends, the only thing I can see is 8 cicc/ptxas processors taking 100% CPU for building, that might be an issue too?

**Comment by forrestjgq** [comment] 2023-10-23 02:08
@juney-nvidia  pls feel free if you need anything to help me solving this issue, we're looking forward to try this project ASAP. thanks!

**Comment by kaiyux** [comment] 2023-10-23 02:44
Hi @forrestjgq , thanks for reporting this.

I can reproduce that line of log, and we may need to fix `cpp/CMakeLists.txt` for that. However, it shouldn't block you from compiling the code, because `nvuffparser` is never used in TRT-LLM. Could you please wait to see if the building process could be successful?

Some cu files indeed take some time when doing the clean build, and the concrete time consuming depends on the hardware that is used. How long did that take you before it's interrupted?

**Comment by forrestjgq** [comment] 2023-10-24 00:27
thanks for your helping, now build passed.

**Comment by kaiyux** [comment] 2023-10-24 02:22
Thanks. We will push updates regarding the `nvparser NOT FOUND` issue.

Closing.

**Closed by kaiyux** 2023-10-24 02:22 UTC
Labels: triaged

**Comment by mingfengwuye** [comment] 2023-10-24 03:30
> Hi @forrestjgq , thanks for reporting this.
> 
> I can reproduce that line of log, and we may need to fix `cpp/CMakeLists.txt` for that. However, it shouldn't block you from compiling the code, because `nvuffparser` is never used in TRT-LLM. Could you please wait to see if the building process could be successful?
> 
> Some cu files indeed take some time when doing the clean build, and the concrete time consuming depends on the hardware that is used. How long did that take you before it's interrupted?

Later, will the parser (onnx parser or other parser) is used to build network ?

**Comment by jdemouth-nvidia** [comment] 2023-10-24 05:15
Hi @mingfengwuye , for now, the models must be built using the Python API in TensorRT-LLM and weights are loaded from checkpoints (HF, Nemo, PyTorch). There is no plan to support ONNX in the near term. Thanks. Julien
