### ISSUE TITLE
segmentation fault : llama 2 with num_beams > 1 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT-LLM#77] opened 2023-10-23 17:16 UTC
run example/llama/run.py with --num_beams 4 will cause an exception:
```
Running the float16 engine ...
[9087e267f1dd:12236] *** Process received signal ***
[9087e267f1dd:12236] Signal: Segmentation fault (11)
[9087e267f1dd:12236] Signal code: Address not mapped (1)
[9087e267f1dd:12236] Failing at address: (nil)
│[9087e267f1dd:12236] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef10)[0x7f76f0772f10]
[9087e267f1dd:12236] [ 1] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x1b9b8)[0x7f76ec6589b8]
[9087e267f1dd:12236] [ 2] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Find_FDE+0xcd)[0x7f76ec65965d]
[9087e267f1dd:12236] [ 3] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x17f0a)[0x7f76ec654f0a]
[9087e267f1dd:12236] [ 4] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_RaiseException+0x1cd)[0x7f76ec6568cd]
[9087e267f1dd:12236] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x37)[0x7f76ea03a1a7]
[9087e267f1dd:12236] [ 6] /mnt0/TensorRT-9.1.0.4/lib/libnvinfer.so.9(+0xf9fcb5)[0x7f75ac8a8cb5]
[9087e267f1dd:12236] *** End of error message ***
Segmentation fault 
```

num_beams=1 is ok. 

- model: llama-7b-hf
- Nvidia driver: 535.104.12 
- cuda: 12.2
- cudnn: 8.9.4.25
- tensorrt: 9.1.0.4

**Comment by byshiue** [comment] 2023-10-23 23:42
Can you share the scripts to build engine and the scripts to run the example?

**Comment by JosephChenHub** [comment] 2023-10-24 02:55
> Can you share the scripts to build engine and the scripts to run the example?

just follow example/llama, use ''float16'' or ''bfloat16'' and llama2-7b-hf

**Comment by byshiue** [comment] 2023-10-24 03:05
> > Can you share the scripts to build engine and the scripts to run the example?
> 
> just follow example/llama, use ''float16'' or ''bfloat16'' and llama2-7b-hf

@JosephChenHub For llama, there are many different configs for different cases. So, when you mention "just follow example/llama", I am not sure what scripts you use. Can you share your scripts directly?

**Comment by jdemouth-nvidia** [comment] 2023-10-24 03:24
As a gentle reminder, we want to help but we also have a lot on our plate. So, it'd be nice if you could provide us with a complete reproducer, please.

**Comment by byshiue** [comment] 2023-11-24 09:45
Close this bug because it is in-activate. If you still encounter any issue, please take a try on latest main branch first. Feel free to reopen it if needed.

**Closed by byshiue** 2023-11-24 09:45 UTC
Labels: triaged
