### ISSUE TITLE
Export logits by gather_all_token_logits met error: [10/25/2023-13:31:55] [TRT-LLM] [E] Those tensors in engine are not expected: {'last_token_ids'}

### ISSUE THREAD

**Issue by starlitsky2010** [NVIDIA/TensorRT-LLM#122] opened 2023-10-25 13:46 UTC
When I make the following modifications:

```
index bb841ed..086fef8 100644
--- a/examples/llama/run.py
+++ b/examples/llama/run.py
@@ -82,7 +82,8 @@ def read_config(config_path: Path):
                                remove_input_padding=remove_input_padding,
                                dtype=dtype,
                                quant_mode=quant_mode,
-                               use_custom_all_reduce=use_custom_all_reduce,)
+                               use_custom_all_reduce=use_custom_all_reduce,
+                               gather_all_token_logits=True)

     return model_config, tp_size, pp_size, dtype

```
Then error occurs, it seems gather_all_token_logits is not working well. Any tips about this?

```
root@769c61956eee:/app/tensorrt_llm/examples/llama# CUDA_VISIBLE_DEVICES=3 python3 run.py --max_output_len=60                --tokenizer_dir /models/Llama-2-7b-chat-hf/               --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
[10/25/2023-13:31:55] [TRT-LLM] [E] The following expected tensors are not found: set()
[10/25/2023-13:31:55] [TRT-LLM] [E] Those tensors in engine are not expected: {'last_token_ids'}
[10/25/2023-13:31:55] [TRT-LLM] [E] Expected tensor names: ['input_ids', 'logits', 'position_ids', 'cache_indirection', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'past_key_value_24', 'past_key_value_25', 'past_key_value_26', 'past_key_value_27', 'past_key_value_28', 'past_key_value_29', 'past_key_value_30', 'past_key_value_31', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'present_key_value_24', 'present_key_value_25', 'present_key_value_26', 'present_key_value_27', 'present_key_value_28', 'present_key_value_29', 'present_key_value_30', 'present_key_value_31',ngths', 'host_context_lengths']
[10/25/2023-13:31:55] [TRT-LLM] [E] Found tensor names: ['input_ids', 'position_ids', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'past_key_value_24', 'past_key_value_25', 'past_key_value_26', 'past_key_value_27', 'past_key_value_28', 'past_key_value_29', 'past_key_value_30', 'past_key_value_31', 'sequence_length', 'host_request_types', 'host_past_key_value_lengths', 'context_lengths', 'host_context_lengths', 'last_token_ids', 'cache_indirection', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'present_key_value_24', 'present_key_value_25', 'present_key_value_26', 'present_key_value_27', 'present_key_value_28', 'present_key_value_29', 'present_key_value_30', 'present_key_value_31', 'logits']
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/run.py", line 273, in <module>
    generate(**vars(args))
  File "/app/tensorrt_llm/examples/llama/run.py", line 237, in generate
    decoder = tensorrt_llm.runtime.GenerationSession(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 432, in __init__
    raise RuntimeError(
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.
```

Thanks

**Comment by jdemouth-nvidia** [comment] 2023-10-25 14:34
Hi @starlitsky2010 , 

If you take a look at the model.py, it does not declare `last_token_ids` when you gather all the logits as the engine will not extract that last token (it’ll return all the logits and the extraction will happen after the TensorRT engine returns). You need to change your code to make sure you don’t try to bind the `last_token_ids` tensor. 

Thanks, Julien

**Comment by Amagong** [comment] 2023-10-31 09:21
Hi @jdemouth-nvidia 

I'd like to see `logits` but can't because of the same issue.
`last_token_ids` seems to be automatically bound inside `tensorrt_llm/runtime/generation.py`. how can I unbind it?

Thanks

**Comment by jdemouth-nvidia** [comment] 2023-10-31 12:58
See that [line](https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/tensorrt_llm/runtime/generation.py#L918). It is not bound if `self.gather_all_token_logits` is set. 

Don’t you agree?

**Comment by Amagong** [comment] 2023-11-01 05:07
Thanks for the reply.
You're right, in that line, if  `self.gather_all_token_logits` is set, it won't bind.

however, if set `gather_all_token_logits=True` in the `ModelConfig` of [TensorRT-LLM/examples/llama/run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/run.py), error occurs.

```
[11/01/2023-05:10:59] [TRT-LLM] [E] The following expected tensors are not found: set()
[11/01/2023-05:10:59] [TRT-LLM] [E] Those tensors in engine are not expected: {'last_token_ids'}
[11/01/2023-05:10:59] [TRT-LLM] [E] Expected tensor names: ['input_ids', 'logits', 'position_ids', 'cache_indirection', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'past_key_value_24', 'past_key_value_25', 'past_key_value_26', 'past_key_value_27', 'past_key_value_28', 'past_key_value_29', 'past_key_value_30', 'past_key_value_31', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'present_key_value_24', 'present_key_value_25', 'present_key_value_26', 'present_key_value_27', 'present_key_value_28', 'present_key_value_29', 'present_key_value_30', 'present_key_value_31', 'sequence_length', 'context_lengths', 'host_request_types', 'host_past_key_value_lengths', 'host_context_lengths']
[11/01/2023-05:10:59] [TRT-LLM] [E] Found tensor names: ['input_ids', 'position_ids', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'past_key_value_24', 'past_key_value_25', 'past_key_value_26', 'past_key_value_27', 'past_key_value_28', 'past_key_value_29', 'past_key_value_30', 'past_key_value_31', 'sequence_length', 'host_request_types', 'host_past_key_value_lengths', 'context_lengths', 'host_context_lengths', 'last_token_ids', 'cache_indirection', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'present_key_value_24', 'present_key_value_25', 'present_key_value_26', 'present_key_value_27', 'present_key_value_28', 'present_key_value_29', 'present_key_value_30', 'present_key_value_31', 'logits']
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /code/tensorrt-llm/examples/llama/run.py:273 in <module>                       │
│                                                                                                  │
│   270                                                                                            │
│   271 if __name__ == '__main__':                                                                 │
│   272 │   args = parse_arguments()                                                               │
│ ❱ 273 │   generate(**vars(args))                                                                 │
│   274                                                                                            │
│                                                                                                  │
│ /code/tensorrt-llm/examples/llama/run.py:234 in generate                       │
│                                                                                                  │
│   231 │   serialize_path = engine_dir / engine_name                                              │
│   232 │   with open(serialize_path, 'rb') as f:                                                  │
│   233 │   │   engine_buffer = f.read()                                                           │
│ ❱ 234 │   decoder = tensorrt_llm.runtime.GenerationSession(model_config,                         │
│   235 │   │   │   │   │   │   │   │   │   │   │   │   │    engine_buffer,                        │
│   236 │   │   │   │   │   │   │   │   │   │   │   │   │    runtime_mapping,                      │
│   237 │   │   │   │   │   │   │   │   │   │   │   │   │    debug_mode=False,                     │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py:430 in __init__       │
│                                                                                                  │
│    427 │   │   │   )                                                                             │
│    428 │   │   │   logger.error(f"Expected tensor names: {expected_tensor_names}")               │
│    429 │   │   │   logger.error(f"Found tensor names: {found_tensor_names}")                     │
│ ❱  430 │   │   │   raise RuntimeError(                                                           │
│    431 │   │   │   │   "Tensor names in engine are not the same as expected, to use this Genera  │
│    432 │   │   │   │   │   "you need to use GPTLMHeadModel.prepare_inputs to create TRT Network  │
│    433 │   │   │   )                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession,
you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.
```

I modified [`here`](https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/examples/llama/run.py#L71C1-L71C1) as below.
I only added `gather_all_token_logits=True`.

    model_config = ModelConfig(num_heads=num_heads,
                               num_kv_heads=num_kv_heads,
                               hidden_size=hidden_size,
                               vocab_size=vocab_size,
                               num_layers=num_layers,
                               gpt_attention_plugin=use_gpt_attention_plugin,
                               paged_kv_cache=paged_kv_cache,
                               tokens_per_block=tokens_per_block,
                               remove_input_padding=remove_input_padding,
                               dtype=dtype,
                               quant_mode=quant_mode,
                               use_custom_all_reduce=use_custom_all_reduce,
                               gather_all_token_logits=True)

and I added `return_dict=True` to the `decode` functions as below.

    output_gen_ids = decoder.decode(input_ids,
                                    input_lengths,
                                    sampling_config,
                                    streaming=streaming,
                                    return_dict=True)


is my approach to getting `logits` wrong?

**Comment by eycheung** [comment] 2023-11-03 17:39
@starlitsky2010 @Amagong 

I ran into this issue as well. To fix this, I believe you will need to rebuild the TRT-Engine with `--gather_all_token_logits` before calling this code.

**NB:** For llama, this flag isn't supported yet, so you'll need to:

- Add the argument in the build script: https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/build.py
- Updated `prepare_inputs` in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/models/llama/model.py#L360 to also accept this flag.

You can look at the gpt example on how they pass `gather_all_token_logits`. I'll try to prepare a PR with this fix as well.

**Comment by Amagong** [comment] 2023-11-06 04:59
> @starlitsky2010 @Amagong
> 
> I ran into this issue as well. To fix this, I believe you will need to rebuild the TRT-Engine with `--gather_all_token_logits` before calling this code.
> 
> **NB:** For llama, this flag isn't supported yet, so you'll need to:
> 
> * Add the argument in the build script: https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/build.py
> * Updated `prepare_inputs` in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/models/llama/model.py#L360 to also accept this flag.
> 
> You can look at the gpt example on how they pass `gather_all_token_logits`. I'll try to prepare a PR with this fix as well.

Thanks to @eycheung , the problem was solved!

**Comment by byshiue** [comment] 2023-12-11 08:24
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 08:24 UTC
Labels: wontfix, triaged
