### ISSUE TITLE
when max_batch_size=1,64,128 in build phrase, the gpu memory will be 27g, 49g, 72g in inference phrase, is this normal?  

### ISSUE THREAD

**Issue by HoursAI** [NVIDIA/TensorRT-LLM#247] opened 2023-11-02 07:02 UTC
I need batch inference, so i set different max_batch_size, like 1, 64, 128. Then I found the gpu memory use will be 27g, 49g, 72g in inference phrase. so i need at least 72g gpu memory to inference when i set batch_size=128. 

And in inference phrase, when I only load one model and run different batch inference, i found the gpu memory use not free-up, but increase.  for example, batch_size=10, sentence_num=100, so i have 10 batches. I load one model and inference these batches in order, i found the gpu memory is increasing all the time, until the end of inference.
is this normal ?

**Comment by jdemouth-nvidia** [comment] 2023-11-02 08:13
Hi @HoursAI ,

Can you share the build commands you are using please? We'll need them to understand the issue.

Thanks,
Julien

**Comment by HoursAI** [comment] 2023-11-02 09:17
> Hi @HoursAI ,
> 
> Can you share the build commands you are using please? We'll need them to understand the issue.
> 
> Thanks, Julien

hi, my build commands are as follows:
python build.py --model_version v2_13b \
                --model_dir /data2/model/baichuan/Baichuan2-13B-Chat \
                --dtype float16 \
                --max_batch_size 128 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./tmp/baichuan_v2_13b/trt_engines/fp16/1-gpu-3/ \
                --use_inflight_batching

I tried three max_batch_size: 1, 64, 128, the bigger max_batch_size, the more gpu memory use in inference phrase.

**Comment by litaotju** [comment] 2023-11-06 05:35
@HoursAI 
> the bigger max_batch_size, the more gpu memory use in inference phrase.
Under the current implementation, this is expected. TRT engine reserves the activation tensor memory based on the max input shapes, to make sure no OOM can happen when such size are specified, and to avoid runtime allocation for perf reason.
Please build the engine with max batch size equals to or close to the actual batch size you use in the runtime.

We may provide options to users to allow the runtime allocation based on actual batch size in the future release.

**Comment by HoursAI** [comment] 2023-11-06 09:11
> @HoursAI
> 
> > the bigger max_batch_size, the more gpu memory use in inference phrase.
> > Under the current implementation, this is expected. TRT engine reserves the activation tensor memory based on the max input shapes, to make sure no OOM can happen when such size are specified, and to avoid runtime allocation for perf reason.
> > Please build the engine with max batch size equals to or close to the actual batch size you use in the runtime.
> 
> We may provide options to users to allow the runtime allocation based on actual batch size in the future release.

ok. thanks! and how about my second question?  as follows:
**And in inference phrase, when I only load one model and run different batch inference, i found the gpu memory use not free-up, but increase. for example, batch_size=10, sentence_num=100, so i have 10 batches. I load one model and inference these batches in order, i found the gpu memory is increasing all the time, until the end of inference.
is this normal ?**

**Comment by litaotju** [comment] 2023-11-08 03:51
> > @HoursAI
> > > the bigger max_batch_size, the more gpu memory use in inference phrase.
> > > Under the current implementation, this is expected. TRT engine reserves the activation tensor memory based on the max input shapes, to make sure no OOM can happen when such size are specified, and to avoid runtime allocation for perf reason.
> > > Please build the engine with max batch size equals to or close to the actual batch size you use in the runtime.
> > 
> > 
> > We may provide options to users to allow the runtime allocation based on actual batch size in the future release.
> 
> ok. thanks! and how about my second question? as follows: **And in inference phrase, when I only load one model and run different batch inference, i found the gpu memory use not free-up, but increase. for example, batch_size=10, sentence_num=100, so i have 10 batches. I load one model and inference these batches in order, i found the gpu memory is increasing all the time, until the end of inference. is this normal ?**

This is not normal. How do you run inference, could you share the code or example command (if you are using the example script) so that we can debug this?

**Comment by HoursAI** [comment] 2023-11-08 08:45
my code is as follows: 
`
import os
import sys
import json
import time

os.environ["CUDA_VISIBLE_DEVICES"] = "1"
import numpy as np
import torch
from transformers import AutoTokenizer

import tensorrt_llm
from tensorrt_llm.runtime import ModelConfig, SamplingConfig

EOS_TOKEN = 2
PAD_TOKEN = 0
LOG_LEVEL = "info"
tensorrt_llm.logger.set_level(LOG_LEVEL)


class BaichuanTRTModel:
    def __init__(self, model_dir: str, model_name: str, tokenizer_dir: str):
        self.model_dir = model_dir
        self.model_name = model_name
        self.tokenizer_dir = tokenizer_dir

        # set runtime rank and mapping and device
        self.runtime_rank = tensorrt_llm.mpi_rank()
        self.runtime_mapping = tensorrt_llm.Mapping()
        torch.cuda.set_device(self.runtime_rank % self.runtime_mapping.gpus_per_node)

        # parser config
        config_path = os.path.join(self.model_dir, 'config.json')
        with open(config_path, 'r') as f:
            self.config = json.load(f)
        self.parse_config()
        self.model_config = ModelConfig(vocab_size=self.vocab_size,
                                        num_layers=self.num_layers,
                                        num_heads=self.num_heads,
                                        num_kv_heads=self.num_heads,
                                        hidden_size=self.hidden_size,
                                        gpt_attention_plugin=self.use_gpt_attention_plugin,
                                        remove_input_padding=self.remove_input_padding,
                                        paged_kv_cache=self.paged_kv_cache,
                                        tokens_per_block=self.tokens_per_block,
                                        dtype=self.dtype,
                                        use_custom_all_reduce=self.use_custom_all_reduce)

        # init tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(self.tokenizer_dir, trust_remote_code=True)

        # init model
        self.serialize_path = os.path.join(self.model_dir, self.model_name)
        with open(self.serialize_path, "rb") as f:
            engine_buffer = f.read()
        self.model = tensorrt_llm.runtime.GenerationSession(self.model_config,
                                                            engine_buffer,
                                                            self.runtime_mapping)

    def parse_config(self):
        self.use_gpt_attention_plugin = self.config["plugin_config"]["gpt_attention_plugin"]
        self.remove_input_padding = self.config["plugin_config"]["remove_input_padding"]
        self.paged_kv_cache = self.config["plugin_config"]["paged_kv_cache"]
        self.tokens_per_block = self.config["plugin_config"]["tokens_per_block"]
        self.dtype = self.config["builder_config"]["precision"]
        self.world_size = self.config["builder_config"]["tensor_parallel"]
        assert self.world_size == tensorrt_llm.mpi_world_size(), \
            f'Engine world size {self.world_size} does not match MPI world size {tensorrt_llm.mpi_world_size()}'
        self.num_heads = self.config["builder_config"]["num_heads"] // self.world_size
        self.hidden_size = self.config["builder_config"]["hidden_size"] // self.world_size
        self.vocab_size = self.config["builder_config"]["vocab_size"]
        self.num_layers = self.config["builder_config"]["num_layers"]
        self.use_custom_all_reduce = self.config["plugin_config"]["use_custom_all_reduce"]

    def single_batch_run(self, querys, max_output_len=100, num_beams=1, temperature=0.3,
                         top_k=5, top_p=0.85, repetition_penalty=1.05):
        sampling_config = SamplingConfig(end_id=EOS_TOKEN,
                                         pad_id=PAD_TOKEN,
                                         num_beams=num_beams,
                                         repetition_penalty=repetition_penalty,
                                         temperature=temperature,
                                         top_k=top_k,
                                         top_p=top_p)
        input_tokens = [self.tokenizer.encode(query, add_special_tokens=False) for query in querys]
        input_lengths = torch.tensor([len(x) for x in input_tokens], dtype=torch.int32, device='cuda')
        if self.remove_input_padding:
            input_ids = np.concatenate(input_tokens)
            input_ids = torch.tensor(input_ids,
                                     dtype=torch.int32,
                                     device='cuda').unsqueeze(0)
        else:
            input_ids = torch.nested.to_padded_tensor(
                torch.nested.nested_tensor(input_tokens, dtype=torch.int32),
                EOS_TOKEN).cuda()
        max_input_length = torch.max(input_lengths).item()
        self.model.setup(input_lengths.size(0), max_input_length, max_output_len, beam_width=num_beams)
        output_ids = self.model.decode(input_ids, input_lengths, sampling_config)
        try:
            outputs = [output_ids[i][0][input_lengths[i]:torch.nonzero(output_ids[i][0] == EOS_TOKEN).squeeze()[0]].tolist()
                       for i in range(len(output_ids))]
        except:
            outputs = [output_ids[i][0][input_lengths[i]:].tolist() for i in range(len(output_ids))]
        output_text = [self.tokenizer.decode(item, skip_special_tokens=True) for item in outputs]
        print(output_text)

    def batch_test(self, input_sequence_num=1024, batch_list=[1]):
        query = "中国的“东北三省”指的是哪里？"
        querys = [f"<reserved_106>{query}<reserved_107>"] * input_sequence_num
        for batch_size in batch_list:
            batches = [querys[i:i + batch_size] for i in range(0, len(querys), batch_size)]
            for i, batch in enumerate(batches):
                if i % 10 == 0:
                    print(f"batch:\t{i}")
                self.single_batch_run(batch)


if __name__ == '__main__':
    model_dir = "./tmp/baichuan_v2_13b/trt_engines/fp16/1-gpu/"
    model_name = "baichuan_float16_tp1_rank0.engine"
    tokenizer_dir = "/data/model/baichuan/Baichuan2-13B-Chat"
    model = BaichuanTRTModel(model_dir, model_name, tokenizer_dir)
    input_sequence_num = 1024
    model.batch_test(input_sequence_num=input_sequence_num, batch_list=[1, 2, 4, 8, 16, 32, 64])
`

is there any problems? thanks!

**Comment by elinx** [comment] 2023-11-08 09:40
> @HoursAI
> 
> > the bigger max_batch_size, the more gpu memory use in inference phrase.
> > Under the current implementation, this is expected. TRT engine reserves the activation tensor memory based on the max input shapes, to make sure no OOM can happen when such size are specified, and to avoid runtime allocation for perf reason.
> > Please build the engine with max batch size equals to or close to the actual batch size you use in the runtime.

I think this is important and should be clearly stated in the documentation; otherwise it's easy to run into issues.

**Comment by litaotju** [comment] 2023-12-05 13:50
> > @HoursAI
> > > the bigger max_batch_size, the more gpu memory use in inference phrase.
> > > Under the current implementation, this is expected. TRT engine reserves the activation tensor memory based on the max input shapes, to make sure no OOM can happen when such size are specified, and to avoid runtime allocation for perf reason.
> > > Please build the engine with max batch size equals to or close to the actual batch size you use in the runtime.
> 
> I think this is important and should be clearly stated in the documentation; otherwise it's easy to run into issues.

I agree with you, and now this is documented in https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/memory.md

**Comment by byshiue** [comment] 2023-12-11 09:21
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Closed by byshiue** 2023-12-11 09:21 UTC
Labels: triaged, Memory
